services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    environment:
      - STEAM_API_KEY=${STEAM_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
      - API_URL=${API_URL}
