FROM python:3.8-slim

RUN apt-get update && apt-get install -y \
    libgomp1 \
    build-essential \
    && rm -rf /var/lib/apt/list/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY . .

ENV PYTHONPATH=/app/arc

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]